Repository BenefitAllyeojyo/2025-BenefitAllyeojyo-14, pull requests merged in 2025-08, with the labels that each got.

#6 [FEAT] 백엔드 프로젝트 초기설정을 수행했습니다. (#3)
  backend/.gitattributes
  backend/.gitignore
  backend/build.gradle
  backend/community/build.gradle
  backend/community/src/main/java/com/heyoung/HeyoungCommunityApplication.java
  backend/core-bank/build.gradle
  backend/core-bank/src/main/java/com/heyoung/HeyoungCoreBankApplication.java
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
Labels: ✨ Feature, 📡 Ba

#33 [FEAT] Postgresql 초기 설정 및 University 더미 데이터 삽입
  backend/community/build.gradle
  backend/community/src/main/resources/data.sql
Labels: ✨ Feature, 📡 Ba

#37 [REFACTOR] : 알림 구현을 위한 테이블 추가 및 컬럼 수정
  backend/.gitignore
  backend/community/build.gradle
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/Category.java
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/Partnership.java
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/PartnershipBranch.java
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/PartnershipImage.java
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/Recommendation.java
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/UniversityPartnership.java
  backend/community/src/main/java/com/heyoung/domain/notification/entity/FcmKey.java
  backend/community/src/main/java/com/heyoung/domain/notification/entity/Notification.java
  backend/community/src/main/java/com/heyoung/domain/notification/entity/NotificationLog.java
  backend/community/src/main/java/com/heyoung/domain/notification/entity/PushToken.java
  backend/community/src/main/java/com/heyoung/domain/recommendation/entity/UserCategory.java
  backend/community/src/main/java/com/heyoung/domain/recommendation/entity/UserHourHist.java
  backend/community/src/main/java/com/heyoung/domain/university/entity/University.java
  backend/community/src/main/java/com/heyoung/domain/university/entity/UniversityStaff.java
  backend/community/src/main/java/com/heyoung/global/entity/BaseEntity.java
  backend/community/src/main/java/com/heyoung/global/enums/HourBucket.java
  backend/community/src/main/java/com/heyoung/global/enums/InvalidType.java
  backend/community/src/main/java/com/heyoung/global/enums/PartnershipCategory.java
  backend/community/src/main/java/com/heyoung/global/enums/UniversityType.java
  backend/community/src/main/resources/data.sql
  backend/community/src/test/java/com/heyoung/HeyoungCommunityApplicationTests.java
  backend/core-bank/build.gradle
  backend/core-bank/src/main/java/com/heyoung/domain/outbox/entity/Outbox.java
  backend/core-bank/src/main/java/com/heyoung/domain/payment/entity/Transaction.java
  backend/core-bank/src/main/java/com/heyoung/global/entity/BaseEntity.java
  backend/core-bank/src/test/java/com/heyoung/HeyoungCoreBankApplicationTests.java
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
Labels: 🔨 Refactor, 📡 Ba

#55 [FEAT] 스웨거 설정 변경
  backend/community/build.gradle
  backend/community/src/main/java/com/heyoung/global/swaggerconfig/SwaggerConfig.java
Labels: ✨ Feature, 📡 Ba

#59 [feat]: 지도 화면 1차 구축 및 API/슬라이딩패널 통합 (#issueNum)
  .vscode/settings.json
  frontend/heyyoung-webapp/index.html
  frontend/heyyoung-webapp/public/mock/mapMarkers.js
  frontend/heyyoung-webapp/src/Components/atoms/Button/CharacterBtn.module.css
  frontend/heyyoung-webapp/src/Components/atoms/Button/MapActionButton.jsx
  frontend/heyyoung-webapp/src/Components/atoms/Button/MapActionButton.module.css
  frontend/heyyoung-webapp/src/Components/atoms/Button/MiniSelectBtn.jsx
  frontend/heyyoung-webapp/src/Components/atoms/Button/MiniSelectBtn.module.css
  frontend/heyyoung-webapp/src/Components/atoms/Button/index.jsx
  frontend/heyyoung-webapp/src/Components/atoms/Input/GptInput.module.css
  frontend/heyyoung-webapp/src/Components/atoms/LocationPin/LocationPin.jsx
  frontend/heyyoung-webapp/src/Components/atoms/LocationPin/LocationPin.module.css
  frontend/heyyoung-webapp/src/Components/atoms/LocationPin/index.jsx
  frontend/heyyoung-webapp/src/Components/molecules/MapGrp/CategoryButtons.jsx
  frontend/heyyoung-webapp/src/Components/molecules/MapGrp/CharacterButtonGroup.jsx
  frontend/heyyoung-webapp/src/Components/molecules/MapGrp/MapView.jsx
  frontend/heyyoung-webapp/src/Components/molecules/MapGrp/MapView.module.css
  frontend/heyyoung-webapp/src/Components/molecules/MapGrp/SlidingPanel.jsx
  frontend/heyyoung-webapp/src/Components/molecules/TextGrp/ToolTipModule.jsx
  frontend/heyyoung-webapp/src/Components/molecules/TextGrp/ToolTipModule.module.css
  frontend/heyyoung-webapp/src/Icons/svg/LocationPin.svg
  frontend/heyyoung-webapp/src/Page/MapTestPage.jsx
  frontend/heyyoung-webapp/src/hooks/folderInfo.md
  frontend/heyyoung-webapp/src/hooks/useStores.js
  frontend/heyyoung-webapp/src/mocks/stores.js
  frontend/heyyoung-webapp/src/services/api/categories.js
  frontend/heyyoung-webapp/src/services/api/index.js
  frontend/heyyoung-webapp/src/services/api/partnerships.js
  frontend/heyyoung-webapp/src/services/api/stores.js
  frontend/heyyoung-webapp/src/services/folderInfo.md
Labels: ✨ Feature, 🖌️ Fe

#58 [FEAT] 카테고리를 통한 검색 기능 추가
  backend/community/src/main/java/com/heyoung/domain/benefit/controller/PartnershipBranchController.java
  backend/community/src/main/java/com/heyoung/domain/benefit/controller/PartnershipController.java
  backend/community/src/main/java/com/heyoung/domain/benefit/dto/BranchInformationDto.java
  backend/community/src/main/java/com/heyoung/domain/benefit/dto/PartnershipDto.java
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/Partnership.java
  backend/community/src/main/java/com/heyoung/domain/benefit/repository/CategoryRepository.java
  backend/community/src/main/java/com/heyoung/domain/benefit/service/PartnershipBranchService.java
  backend/community/src/main/java/com/heyoung/domain/benefit/service/PartnershipService.java
  backend/community/src/main/java/com/heyoung/global/webconfig/CorsConfig.java
  backend/community/src/main/java/com/heyoung/global/webconfig/ManagerId.java
  backend/community/src/main/java/com/heyoung/global/webconfig/MemberId.java
  backend/community/src/main/resources/data.sql
  backend/core-bank/src/main/java/com/heyoung/global/enums/BankCode.java
Labels: ✨ Feature, 📡 Ba

#64 [TEST] 깃허브 액션 배포 로직 작성
  .github/workflows/backend_community_cd_flow.yml
  .github/workflows/backend_core_bank_cd_flow.yml
Labels: ✨ Feature, 📡 Ba, 👷CICD

#74 [FEAT] 커뮤니티에서 코어뱅크로 qr생성 API 호출
  backend/community/src/main/java/com/heyoung/domain/payment/client/TransactionClient.java
  backend/community/src/main/java/com/heyoung/domain/payment/controller/PaymentController.java
  backend/community/src/main/java/com/heyoung/domain/payment/dto/PaymentRequestDto.java
  backend/community/src/main/java/com/heyoung/domain/payment/dto/PaymentResponseDto.java
  backend/community/src/main/java/com/heyoung/domain/payment/dto/QrDataDto.java
  backend/community/src/main/java/com/heyoung/domain/payment/service/PaymentService.java
  backend/community/src/main/java/com/heyoung/global/exception/BaseResponse.java
  backend/community/src/main/java/com/heyoung/global/webconfig/RestTemplateConfig.java
Labels: ✨ Feature, 📡 Ba

#84 [FIX] 앱 기반 렌더링을 위한 이미지와 캐릭터 이미지 변경
  frontend/heyyoung-webapp/src/App.jsx
  frontend/heyyoung-webapp/src/Components/molecules/PaymentGuide/PaymentGuide.module.css
  frontend/heyyoung-webapp/src/Page/BenefitMainPage.jsx
  frontend/heyyoung-webapp/src/Page/EntireMenuPage.jsx
  frontend/heyyoung-webapp/src/Page/MainHomePage.jsx
  frontend/heyyoung-webapp/src/Page/MapView.jsx
  frontend/heyyoung-webapp/src/Page/NotificationPage.jsx
  frontend/heyyoung-webapp/src/Page/PartnershipListPage.jsx
  frontend/heyyoung-webapp/src/Page/Payment.jsx
  frontend/heyyoung-webapp/src/Page/PaymentPage.jsx
  frontend/heyyoung-webapp/src/Page/PaymentResultPage.jsx
  frontend/heyyoung-webapp/src/Page/StoreDetailPage.jsx
  frontend/heyyoung-webapp/src/assets/images/logo.png
  frontend/heyyoung-webapp/src/assets/images/pages/entire-menu.PNG
Labels: 🖌️ Fe

#93 [REFACTOR] 제휴 글에 제휴 주최자 추가
  backend/community/src/main/java/com/heyoung/domain/benefit/dto/BranchInformationDto.java
  backend/community/src/main/java/com/heyoung/domain/benefit/dto/PartnershipBranchDto.java
  backend/community/src/main/java/com/heyoung/domain/benefit/dto/PartnershipDto.java
  backend/community/src/main/java/com/heyoung/domain/benefit/entity/Partnership.java
  backend/community/src/main/resources/data.sql
Labels: 🔨 Refactor, 📡 Ba

#105 [FEAT] 알림 리마인드 기능 구현
  backend/community/src/main/java/com/heyoung/domain/benefit/repository/PartnershipBranchRepository.java
  backend/community/src/main/java/com/heyoung/domain/benefit/service/PartnershipBranchService.java
  backend/community/src/main/java/com/heyoung/domain/notification/controller/NotificationController.java
  backend/community/src/main/java/com/heyoung/domain/notification/dto/response/GetNotificationByRemindResponseDto.java
  backend/community/src/main/java/com/heyoung/domain/notification/dto/response/GetNotificationListByUserResponseDto.java
  backend/community/src/main/java/com/heyoung/domain/notification/entity/NotificationLog.java
  backend/community/src/main/java/com/heyoung/domain/notification/exception/NotificationException.java
  backend/community/src/main/java/com/heyoung/domain/notification/repository/NotificationLogRepository.java
  backend/community/src/main/java/com/heyoung/domain/notification/repository/NotificationRepository.java
  backend/community/src/main/java/com/heyoung/domain/notification/service/NotificationLogCommandService.java
  backend/community/src/main/java/com/heyoung/domain/notification/service/NotificationLogCommandServiceImpl.java
  backend/community/src/main/java/com/heyoung/domain/notification/service/NotificationQueryService.java
  backend/community/src/main/java/com/heyoung/domain/notification/service/NotificationQueryServiceImpl.java
  backend/community/src/main/java/com/heyoung/domain/notification/service/converter/NotificationLogConverter.java
  backend/community/src/main/java/com/heyoung/global/exception/ResponseCode.java
  backend/community/src/main/resources/data.sql
Labels: ✨ Feature, 📡 Ba

#111 [REFACTOR] 제휴 추천을 위한 사용자 선호도 반영 가중치 개선
  backend/community/src/main/java/com/heyoung/domain/benefit/exception/advice/PartnershipException.java
  backend/community/src/main/java/com/heyoung/domain/benefit/repository/PartnershipNearbyRepository.java
  backend/community/src/main/java/com/heyoung/domain/benefit/service/PartnershipService.java
  backend/community/src/main/java/com/heyoung/domain/notification/repository/NotificationAggRepository.java
  backend/community/src/main/java/com/heyoung/domain/notification/service/DailyNotificationSchedulerImpl.java
  backend/community/src/main/java/com/heyoung/domain/recommendation/repository/UserPreferenceReadRepository.java
  backend/community/src/main/java/com/heyoung/global/exception/ResponseCode.java
  backend/community/src/main/resources/data.sql
Labels: 🔨 Refactor, 📡 Ba
